on: 
 push:
  branches:
    - master








jobs:
 build:
  runs-on: ubuntu-latest


  steps:
    - name: 'testing action'
      run: pwd

    - name: 'testing printing'
      run: echo ali

    - name: 'printing folder contents'
      run: ls

    - uses: actions/checkout@v3

    - name: 'printing folder contents'
      run: ls



